# Generated by Django 5.2.5 on 2025-10-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='projects_gifs/'),
        ),
    ]
