# Generated by Django 5.2.5 on 2025-10-23 09:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_project_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gif',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gif'),
        ),
    ]
